included:
  - Sources
  - Tests
  
excluded:
  - Packages
  - .build

opt_in_rules:
  - empty_count
  - force_unwrapping
  - file_header

force_cast: warning

function_body_length:
  warning: 50

identifier_name:
  min_length:
    error: 3
  excluded:
    - sb
    
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SwiftyBeaverProvider
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Sebastian Kreutzberger\. Some rights reserved\.

reporter: "emoji"